### ISSUE TITLE
cant search other language versions

### ISSUE THREAD

**Issue by baruchlab** [cosmocode/dokuwiki-plugin-elasticsearch#10]
hi, I am making a multi-language wiki which is something like a glossary. I need people to be able to search in their own language and find the pertinent article, but search only works for the english article. i.e. it only seems to search the namespace name of the article (the one which appears in the url. 

I'll give an example: 
the EN article is "Abyss", the DE is "Abgrund", the PT is "Abismo", I can't find the latter two through the search box... can you help?

**Comment by baruchlab** [comment]
also it doesn't seem to work 
<img width="946" alt="Screen Shot 2020-06-09 at 03 13 59" src="https://user-images.githubusercontent.com/342640/84095391-78ffb500-a9ff-11ea-8c24-3c37892ae22a.png">

**Comment by splitbrain** [comment]
From your second comment it seems you don't have a Elastic Search server set up and running, so I assume the issue in your first comment isn't a valid issue with this plugin?

**Comment by splitbrain** [comment]
closing this because no additional feedback was given
